library(RSelenium)
remDr <- remoteDriver(remoteServerAddr = "192.168.99.100",port = 4445L)
remDr$open(silent = TRUE)
remDr$navigate("https://www.instagram.com/")
hoook <- remDr$findElement(using = 'css', value = '._fcn8k')
hoook$clickElement()
remDr$sendKeysToActiveElement(list("marta_mackowiak_photography", "\u0009", "marmac12409", "\uE007"))
webElem <- remDr$findElement('xpath', "//input[@placeholder='Search']")
#webElem$highlightElement()
webElem$clickElement()

hoook <- remDr$findElement(using = 'css', value = '._9x5sw')
#hoook$highlightElement()
hoook$clickElement()
remDr$sendKeysToActiveElement(list("photoshoot", "\uE007"))
remDr$sendKeysToActiveElement(list("\uE007"))
pics <- remDr$findElements(using = 'css', value = "._sai17+ div ._ovg3g")
ppp <- remDr$findElements('css', value = 'a')
for(i in 11:21){
  remDr$navigate(ppp[[i]]$getElementAttribute('href')[[1]])
  followButton <- remDr$findElement('css', value = '._rmr7s')
  followButton$highlightElement()
  followButton$clickElement()
  Sys.sleep(3)
}
